name: ProtocolLib
version: ${version}
description: Provides read/write access to the Minecraft protocol.
authors: [dargen, dmulloy2, comphenix]

main: com.comphenix.protocol.ProtocolLib
load: STARTUP
database: false
api-version: "1.13"